### ISSUE TITLE
Message size definition bits or bytes?

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [UAVCAN/nunavut#114]
I've been verifying the PX4 UAVCAN v1 implementation and noticed a bug in that implementation that the messages were to big (8 times to be exactly). It seems this was caused by confusion between the message size generated using nunavut with following template.

`static constexpr size_t SIZE = {{total_size.value}};`

And the payload size definition used in libcanard; to clarify the message size was bits and the payload is defined in bytes.

Question: what would be the best solution to solve this issue?

1. Change total_size.value definition in nunavut
2. Change the template by dividing by 8 e.g.
`static constexpr size_t SIZE = {{total_size.value // 8}};`
3. Divide the size by 8 when assigning the payload size e.g.
`.payload_size   = uavcan::node::Heartbeat_1_0::SIZE / 8,`

My personal preference would be to go for option 1 or option 2, mostly because I would expect that a size variable would be in bytes; but that's just a personal preference.

**Comment by pavel-kirienko** [comment]
DSDL is a bit-level format so whenever we mention the size of anything we mean bits.

The UAVCAN transports and most UAVCAN applications operate on bytes.

To avoid confusion, the unit of size should be mentioned explicitly unless it can be unambiguously determined from the context. For example, in PyUAVCAN the unit is stated explicitly:

- https://github.com/UAVCAN/pyuavcan/blob/a38ce614162be948f61f421eebe1c903389dd578/pyuavcan/dsdl/_templates/base.j2#L412
- https://github.com/UAVCAN/pyuavcan/blob/a38ce614162be948f61f421eebe1c903389dd578/pyuavcan/dsdl/_serialized_representation/_serializer.py#L27

In PyDSDL bits are assumed because they are used consistently throughout. I believe that Nunavut is also consistent in its reliance on bits rather than bytes; regardless of that, changing the definition of total size would be a mistake because it would destroy information if the size is not a multiple of 8.

I recommend you modify your template as follows:

```c
static constexpr std::size_t _MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES_ = {{(total_size.value + 7) // 8}};
```

You should not name the member `SIZE`, it's bad API design because:

1. It is not the size but the *maximum serialized size*. For the object size, there is a `sizeof`.
2. The unit is ambiguous.
3. There will be a naming conflict if the source DSDL defines an attribute named SIZE. `_SIZE_` would work because it is a reserved name but see above.

**Comment by thirtytwobits** [comment]
As I was commenting on the px4 review, should we avoid size_t when storing bit offsets since this is scaled based on a target system's largest possible address in bytes?

**Comment by pavel-kirienko** [comment]
> should we avoid size_t when storing bit offsets

Maybe a build option allowing the developer to use `uint32_t` instead of `size_t` would save us all?

**Comment by thirtytwobits** [comment]
> > should we avoid size_t when storing bit offsets
> 
> Maybe a build option allowing the developer to use `uint32_t` instead of `size_t` would save us all?

Yeah. We could add a named type (e.g. https://github.com/UAVCAN/nunavut/blob/master/src/nunavut/lang/properties.ini#L195) for "bit_size_t" or "bit_length"
