### ISSUE TITLE
test_serialization.c cov_all_archive testVoidZeroed:FAIL

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [UAVCAN/nunavut#149]
I've merged this repo and @davidlenfesty into my own repo (https://github.com/PetervdPerk-NXP/nunavut) and did some fixes but I can't get around this problem.
Unfortunely I'm not familair enough with the DSDL serialization but it seems that nunavutSetBit doesn't return 0x00 as required in this test
```
/repo/verification/c/suite/test_serialization.c:26:testVoidZeroed:FAIL: Expected 0x00 Was 0x7E
/repo/verification/c/suite/test_serialization.c:107:testVariablePrimitiveArrayLength:PASS
/repo/verification/c/suite/test_serialization.c:108:testArrayOverflow:PASS
/repo/verification/c/suite/test_serialization.c:109:testInvalidTag:PASS
/repo/verification/c/suite/test_serialization.c:110:testCompositeLength:PASS
-----------------------
5 Tests 1 Failures 0 Ignored 
```

**Comment by davidlenfesty** [comment]
It appears the test is invalid with a recent DSDL change.

Bit_1_0 used to be
```
bool value
void7 blank # or something
```

Now it is simply
```
bool value
```

The intent with the test was to ensure void types were zeroed out as per the spec.

We should remove the AND mask from the first test assertion and move the test to some data type that has or is void. I think `uavcan.metatransport.can.Error` would work well for us, since I'm assuming it should will always be void.

This brings up another issue, padding bits at the end of a message should all be cleared. We don't do this currently.

We should probably basically just rename this test to `testPaddingZeroed` or something and create a new test to actually test clearing `void`s.

**Comment by PetervdPerk-NXP** [comment]
`uavcan.metatransport.can.Error` generates this struct for me 
```typedef struct
{
} uavcan_metatransport_can_Error_0_1;```

Thus no void in there.

@pavel-kirienko can we remove the testVoidZeroed test?
If I run my branch (which fixed #150 ) without it the cov_all_archive test will succeed

**Comment by pavel-kirienko** [comment]
Yes, I have already done this on my branch. This issue is no longer valid. As discussed yesterday, I will soon provide a list of things that my effort needs help with.

**Comment by pavel-kirienko** [comment]
This is my branch btw https://github.com/UAVCAN/nunavut/tree/c-serialization-corrections
